site_name: MagestoreDocs
docs_dir: extensions
site_url: https://docs.magestore.com
repo_name: 'GitHub'
site_description: 'Magestore Documents'
#theme: readthedocs
#theme:
#    name: mkdocs
#    custom_dir: mytheme/
#    static_templates:
#        - sitemap.html
#    include_sidebar: false

extra_css:
    - css/extra.css
extra_javascript: 
    - js/extra.js
extra:
    version: 1.0
